# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.19.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [45]:
a = np.random.random((2,3,5))
a

array([[[0.24378898, 0.56090186, 0.21651593, 0.07740436, 0.0568608 ],
        [0.03123124, 0.7019853 , 0.47127175, 0.59374347, 0.86614783],
        [0.32538374, 0.256171  , 0.12676298, 0.01987238, 0.35913956]],

       [[0.81131396, 0.12551257, 0.81550582, 0.54526635, 0.37695554],
        [0.6856947 , 0.96129555, 0.43384217, 0.42332409, 0.49464326],
        [0.60668046, 0.3159333 , 0.52426685, 0.53545079, 0.6679694 ]]])

In [47]:
a2 = [[1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9],
      [1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9],
      [1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9],
      
      [1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9],
     [1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9],
      [1,2,3],[4,5,6],[7,8,9],[4,5,6],[7,8,9]
      
]
a2 = np.array(lst_lst)
print(a2)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]
 [ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]


In [46]:
a3 = np.random.randint(0, 10, size=(2, 3, 5))

#### 4. Print *a*.


In [17]:
print(a)

[[[3 6 9]
  [5 4 2]]

 [[9 3 7]
  [5 2 2]]

 [[3 5 8]
  [3 6 4]]

 [[3 2 1]
  [0 9 5]]

 [[8 9 5]
  [7 9 6]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [48]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [39]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [49]:
a.shape

(2, 3, 5)

In [50]:
b.shape

(5, 2, 3)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [31]:
#No we can't add a and b because they don't have the same size.

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [55]:
c = b.reshape(2, 3, 5)
c.shape


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [57]:
d = a+c
#Now, a and c have the same size.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
print(a)

[[[0.24378898 0.56090186 0.21651593 0.07740436 0.0568608 ]
  [0.03123124 0.7019853  0.47127175 0.59374347 0.86614783]
  [0.32538374 0.256171   0.12676298 0.01987238 0.35913956]]

 [[0.81131396 0.12551257 0.81550582 0.54526635 0.37695554]
  [0.6856947  0.96129555 0.43384217 0.42332409 0.49464326]
  [0.60668046 0.3159333  0.52426685 0.53545079 0.6679694 ]]]


In [59]:
print(d)

[[[1.24378898 1.56090186 1.21651593 1.07740436 1.0568608 ]
  [1.03123124 1.7019853  1.47127175 1.59374347 1.86614783]
  [1.32538374 1.256171   1.12676298 1.01987238 1.35913956]]

 [[1.81131396 1.12551257 1.81550582 1.54526635 1.37695554]
  [1.6856947  1.96129555 1.43384217 1.42332409 1.49464326]
  [1.60668046 1.3159333  1.52426685 1.53545079 1.6679694 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [60]:
e= a*c

In [61]:
print(e)

[[[0.24378898 0.56090186 0.21651593 0.07740436 0.0568608 ]
  [0.03123124 0.7019853  0.47127175 0.59374347 0.86614783]
  [0.32538374 0.256171   0.12676298 0.01987238 0.35913956]]

 [[0.81131396 0.12551257 0.81550582 0.54526635 0.37695554]
  [0.6856947  0.96129555 0.43384217 0.42332409 0.49464326]
  [0.60668046 0.3159333  0.52426685 0.53545079 0.6679694 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# e is equal to a. Multiply a matrix by an other matrix of 1, the result is the matrix herself.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
np.max(d)

1.9612955481176826

In [63]:
np.min(d)

1.019872380936599

In [65]:
np.mean(d)

1.441027866424773

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [70]:
f= np.empty((2,3,5))
f

array([[[0.24378898, 0.56090186, 0.21651593, 0.07740436, 0.0568608 ],
        [0.03123124, 0.7019853 , 0.47127175, 0.59374347, 0.86614783],
        [0.32538374, 0.256171  , 0.12676298, 0.01987238, 0.35913956]],

       [[0.81131396, 0.12551257, 0.81550582, 0.54526635, 0.37695554],
        [0.6856947 , 0.96129555, 0.43384217, 0.42332409, 0.49464326],
        [0.60668046, 0.3159333 , 0.52426685, 0.53545079, 0.6679694 ]]])

In [ ]:
# your code here

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
 for i in d:
    for j in i:
        if np.min(d)<np.mean(d):
            f.insert(25)
    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here